### PR TITLE
Problem: self hosted runner does not work

### PR DESCRIPTION
**Pull request by thomas-nguy**
revert to non hosted

### CODE REVIEW

**Comment by thomas-nguy** [comment]
need maybe an archive node to be able to run the ethereum docker

**Comment by thomas-nguy** [comment]
move out from draft status, 

I will fix the integration tests in another PR, but at least this PR should fix the failing build

**Review by tomtau — APPROVED** [review]

**Comment by tomtau** [comment]
the happy path fails though: https://github.com/crypto-org-chain/gravity-bridge/actions/runs/3094788707/jobs/5008773403 so it needs a full node access?

**Comment by thomas-nguy** [comment]
yes seems like the tests is based on some ethereum past state.

the archive node could be set here or as build env variable
https://github.com/crypto-org-chain/gravity-bridge/blob/v2.0.0-cronos/integration_tests/ethereum/Dockerfile#L14

https://github.com/crypto-org-chain/gravity-bridge/blob/v2.0.0-cronos/integration_tests/setup_test.go#L427

**Pull request merged**
