### PR TITLE
Update code for relayerAdmin

### PR DESCRIPTION
**Pull request by FrancoCRO**

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
@FrancoCRO could you provide some more descriptive commit message? what was the issue / how the code was updated?

**Comment by tomtau** [comment]
FYI @FinnZhangCrypto @dandan456

**Comment by thomas-nguy** [comment]
Is it possible with current setting to disable the ACL if we want to open to contract in the future?

**Comment by FrancoCRO** [comment]
Some background about this PR
There are 2 authentication modules in this code: AccessControl (Role) and Ownable

Ownable set contract deployer as `owner` which can call `pause()` and `unpause()`, ownership is transferrable.

AccessControl is more hierarchical, there are 2 roles out there: `RELAYER_ADMIN` and `RELAYER`.
`RELAYER_ADMIN` can assign/revoke anyone to be `RELAYER`, 
`RELAYER` can call those relayer functions.

By the original design from Openzeppelin, the role cannot be transferred, so I add a little tweak here: `RELAYER_ADMIN` is it's own admin. So existing relayerAdmin can make other accounts relayerAdmin, then revoke it's own admin right at the same time.

**Comment by FrancoCRO** [comment]
Having such feature makes @thomas-nguy's suggestion possible.

When we're confident that everyone could be relayer, we can assign a contract address as relayer admin, inside the contract there is:
```
function makeMeRelayer () public {
  setRole(RELAYER, msg.sender);
}
```

Hence, by calling relayerAdmin contract, anyone could be relayer in on-request basis.

**Comment by dandan456** [comment]
> Some background about this PR There are 2 authentication modules in this code: AccessControl (Role) and Ownable
> 
> Ownable set contract deployer as `owner` which can call `pause()` and `unpause()`, ownership is transferrable.
> 
> AccessControl is more hierarchical, there are 2 roles out there: `RELAYER_ADMIN` and `RELAYER`. `RELAYER_ADMIN` can assign/revoke anyone to be `RELAYER`, `RELAYER` can call those relayer functions.
> 
> By the original design from Openzeppelin, the role cannot be transferred, so I add a little tweak here: `RELAYER_ADMIN` is it's own admin. So existing relayerAdmin can make other accounts relayerAdmin, then revoke it's own admin right at the same time.

Looks good

**Pull request merged**
