### PR TITLE
Problem: event handle method should return error only in case of irrecoverable errors

### PR DESCRIPTION
**Pull request by thomas-nguy**
Solution: return nil and log error instead

### CODE REVIEW

**Review by tomtau — APPROVED** [review]

**Comment by tomtau** [comment]
any test for this?

**Comment by thomas-nguy** [comment]
yes, I have added an integration test in cronos
https://github.com/crypto-org-chain/cronos/pull/810

**Review by brianatcrypto — COMMENTED** [review]
@thomas-nguy for these two other cases, should we do the same to log error and return nil?
https://github.com/crypto-org-chain/gravity-bridge/blob/dd0dab3e9b60480b07bc844d75f083a07b7e1977/module/x/gravity/keeper/ethereum_event_handler.go#L55

https://github.com/crypto-org-chain/gravity-bridge/blob/dd0dab3e9b60480b07bc844d75f083a07b7e1977/module/x/gravity/keeper/ethereum_event_handler.go#L59

For instance SendCoinsFromModuleToAccount will throw error if the recipient address is a 'blocked address'. refer the code below.
https://github.com/cosmos/cosmos-sdk/blob/main/x/bank/keeper/keeper.go#L316 

Similarly for minting, https://github.com/crypto-org-chain/gravity-bridge/blob/dd0dab3e9b60480b07bc844d75f083a07b7e1977/module/x/gravity/keeper/ethereum_event_handler.go#L49.
I am not sure if externally one can control the input to result in error for minting.
https://github.com/cosmos/cosmos-sdk/blob/main/x/bank/keeper/keeper.go#L400

**Comment by thomas-nguy** [comment]
I think it is still better to disable the bridge (return error) when the minting function or the transfer function from module to account fails `generally` otherwise we may end up in a corrupted state when tokens is locked to the bridge contract but no tokens is minted on our side.

For predictable case where it could fails such as the recipient address is a 'blocked address', we can add an additional check on the recipient address and return nil in that case.

If we can find other predictable case of errors for minting which are not critical, we can also do the same

**Comment by thomas-nguy** [comment]
@brianatcrypto addressed in this PR

https://github.com/crypto-org-chain/gravity-bridge/pull/200

**Pull request merged**
