### PR TITLE
Problem: automated release fails

### PR DESCRIPTION
**Pull request by thomas-nguy**
Solution : 
- add permission to the gitflow
- remove non existing file
- resync the package-lock.json

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
solidity build etc. fail https://github.com/crypto-org-chain/gravity-bridge/actions/runs/3259849316/jobs/5352980134 or is it unrelated?

**Comment by thomas-nguy** [comment]
yes it is not related , it is waiting for a host to pick it up

I have created a draft for this
https://github.com/crypto-org-chain/gravity-bridge/pull/122

**Review by tomtau — DISMISSED** [review]
I have no way of telling whether this PR is ok -- all it does is to update the solidity dependencies, but solidity/hardhat CI pipelines fail. feel free to merge it, but it's better to do this after those CI pipelines are fixed

**Comment by thomas-nguy** [comment]
https://github.com/crypto-org-chain/gravity-bridge/actions/runs/3259849317

I have triggered the release using a tag over this branch, this PR is just porting the fixes after some trials

**Review by tomtau — DISMISSED** [review]

**Review by tomtau — COMMENTED** [review]
yarn.lock has quite a few vulnerable dependencies, can those be fixed?

**Comment by thomas-nguy** [comment]
yes, done.

I have rerun yarn upgrade and it seems to have fixed the critical vulnerabilities

**Review by tomtau — APPROVED** [review]

**Pull request merged**
