### PR TITLE
Problem: upstream v0.2.14 release is not merged

### PR DESCRIPTION
**Pull request by yihuang**
It fixed several issues we are interested:
- update to cosmos-sdk 0.44.1, https://github.com/crypto-org-chain/cronos/pull/131
- support "run the oracle and signer without the relayer to Ethereum" https://github.com/crypto-org-chain/gravity-bridge/pull/11

### CODE REVIEW

**Comment by yihuang** [comment]
Maybe better to do a rebase to keep history cleaner?

**Review by tomtau — COMMENTED** [review]
> Maybe better to do a rebase to keep history cleaner?

do you mean rebase changes of cronos branch onto main brach of peggyjv?

**Comment by yihuang** [comment]
> > Maybe better to do a rebase to keep history cleaner?
> 
> do you mean rebase changes of cronos branch onto main brach of peggyjv?

yeah, I'm not sure, maybe postpone the rebase after most of our changes are merged in upstream.

**Comment by tomtau** [comment]
ok, perhaps delay it then. for this PR, ok to just merge it -- will the head be buildable?

**Comment by yihuang** [comment]
> ok, perhaps delay it then. for this PR, ok to just merge it -- will the head be buildable?

yeah, it's used in this PR: https://github.com/crypto-org-chain/cronos/pull/131

**Pull request merged**
