### PR TITLE
Problem: gravity-bridge orchestrators don't reject unprofitable messages from cronos to ethereum

### PR DESCRIPTION
**Pull request by thomas-nguy**
cherry-pick from https://github.com/crypto-org-chain/gravity-bridge/pull/9

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
as on the original PR -- it may be good to add an option to be able to switch it off (i.e. switch on the previous non-incentivized processing)

**Comment by thomas-nguy** [comment]
I have added a boolean in the command line to control the relaying fee.

Note : relayer build is failing, trying to fix it atm

**Comment by thomas-nguy** [comment]
ok it is fixed (needed to enable the feature)

**Comment by thomas-nguy** [comment]
closing this for https://github.com/crypto-org-chain/gravity-bridge/pull/36 which point to latest updated branch

**Pull request closed without merging**
