### PR TITLE
Problem: validators are not sorted by checksum address

### LINKED ISSUE #427: Problem on ordering valset
When creating a valset tx, we are sorting valset (or signer set) using string sorting in golang  (On the ethereum address in case of same validators having the same power).

```
func EthereumAddrLessThan(e, o string) bool {
	return bytes.Compare([]byte(e)[:], []byte(o)[:]) == -1
}
``` 

This will result 

```
0x8D6d2605550c6AFbf0669E340d9Eb90372A06a9d < 0x8c474b92c315FEdBef9b1DaFEe0D5DB45575Ed5C
```

However in rust, the address is deserialized to an H160 (case insensitive), and when checking is correct, it will expect 

```
0x8c474b92c315fedbef9b1dafee0d5db45575ed5c < 0x8d6d2605550c6afbf0669e340d9eb90372a06a9d
```

This will result frequent warning such as and may block the valset updating?

```
Jul 04 14:43:08 ip-10-202-3-42 gorc[174678]: 2022-07-04T14:43:08.478362Z  WARN gravity_utils::types::ethereum_events: Someone submitted an unsorted validator set, this means all updates will fail until someone feeds in this unsorted value by hand 
[
ValsetMember { power: 1297573200, eth_address: Some(0x5044c263c810554dd4fd33fa5f303c412b5c350b) },
ValsetMember { power: 1297573200, eth_address: Some(0x5be487aec16780e7d38beb3ca56c90b1b562a53b) },
ValsetMember { power: 1297573200, eth_address: Some(0xa198923ddac5dee8df1009c85315781c7fcb7bc1) },
ValsetMember { power: 77854392, eth_address: Some(0xef450b7a2c5394ddf923b17cf7be08a30ff94c0d) },
ValsetMember { power: 64878660, eth_address: Some(0x0712ec6f893d306f0fe1a6de062ce7cd8a6556ae) },
ValsetMember { power: 64878660, eth_address: Some(0x66d74eca51ea8f1df7510454002191c6769915a8) },
ValsetMember { power: 64878660, eth_address: Some(0x8d6d2605550c6afbf0669e340d9eb90372a06a9d) },
ValsetMember { power: 64878660, eth_address: Some(0x8c474b92c315fedbef9b1dafee0d5db45575ed5c) },
ValsetMember { power: 64878660, eth_address: Some(0xee4b98cb5f57e2bf1dade9e794f7c92e500b0d2b) }
]
instead of 
[
ValsetMember { power: 1297573200, eth_address: Some(0x5044c263c810554dd4fd33fa5f303c412b5c350b) },
ValsetMember { power: 1297573200, eth_address: Some(0x5be487aec16780e7d38beb3ca56c90b1b562a53b) },
ValsetMember { power: 1297573200, eth_address: Some(0xa198923ddac5dee8df1009c85315781c7fcb7bc1) },
ValsetMember { power: 77854392, eth_address: Some(0xef450b7a2c5394ddf923b17cf7be08a30ff94c0d) },
ValsetMember { power: 64878660, eth_address: Some(0x0712ec6f893d306f0fe1a6de062ce7cd8a6556ae) },
ValsetMember { power: 64878660, eth_address: Some(0x66d74eca51ea8f1df7510454002191c6769915a8) },
ValsetMember { power: 64878660, eth_address: Some(0x8c474b92c315fedbef9b1dafee0d5db45575ed5c) },
ValsetMember { power: 64878660, eth_address: Some(0x8d6d2605550c6afbf0669e340d9eb90372a06a9d) },
ValsetMember { power: 64878660, eth_address: Some(0xee4b98cb5f57e2bf1dade9e794f7c92e500b0d2b) }
]
```

### PR DESCRIPTION
**Pull request by thomas-nguy**
Fix https://github.com/PeggyJV/gravity-bridge/issues/427

### CODE REVIEW

**Comment by thomas-nguy** [comment]
Seems that it is picking the permission correctly this time 

```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  Packages: write
  
 ```

**Review by tomtau — APPROVED** [review]

**Comment by tomtau** [comment]
good that permissions work now, but I guess we don't have any "self-hosted" runner, so that job is stuck forever?

**Comment by thomas-nguy** [comment]
seems right.

need to check how to fix this on this repo

**Review by calvinaco — APPROVED** [review]
LGTM

**Pull request merged**
