### PR TITLE
Problem: destination address is not validated for SendToEthereum

### PR DESCRIPTION
**Pull request by thomas-nguy**
Solution: add validation

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
I think go-ethereum is one of dependencies, so why not just use its address type that has these validations?

**Comment by thomas-nguy** [comment]
it is using the geth `common.IsHexAddress` under the hood, but add an additional `hex.DecodeString` for more strong error reporting.

I kept the original comment from the auditor.

**Review by WilliamXieCrypto — COMMENTED** [review]
LGTM

**Review by tomtau — APPROVED** [review]
maybe some test cases based on the audit feedback if the Geth one is ignoring them? 
and should this also enforce the addresses are "normalized" in one form (e.g. eip-55 and verify the checksum matches)?

**Comment by thomas-nguy** [comment]
for SendToEthereum destination address, we don't need to normalized as it is handled by the ethereum side. Both convention works

**Pull request merged**
